In [1]:
!pip install langchain-text-splitters

Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain-text-splitters) (1.4.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.10.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.13.4)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.1.1)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.14.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.32.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.8.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=3.5.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.5.0)
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: langchain-text-splitters
Successfully installed langchain-text-splitters-1.1.2

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import os

print(os.listdir(TEXT_PATH))

['paper1.txt', 'paper10.txt', 'paper2.txt', 'paper3.txt', 'paper4.txt', 'paper5.txt', 'paper6.txt', 'paper7.txt', 'paper8.txt', 'paper9.txt']

In [7]:
from pathlib import Path
import pandas as pd

from langchain_text_splitters import RecursiveCharacterTextSplitter

In [8]:
PROJECT_PATH = Path("/content/drive/MyDrive/uterine-emg-rag")

TEXT_PATH = PROJECT_PATH / "text"

print(TEXT_PATH)

/content/drive/MyDrive/uterine-emg-rag/text

In [9]:
txt_files = sorted(TEXT_PATH.glob("*.txt"))

print(f"Found {len(txt_files)} text files\n")

for file in txt_files:
    print(file.name)

Found 10 text files

paper1.txt
paper10.txt
paper2.txt
paper3.txt
paper4.txt
paper5.txt
paper6.txt
paper7.txt
paper8.txt
paper9.txt

In [10]:
sample_file = txt_files[0]

with open(sample_file, "r", encoding="utf-8") as f:
    text = f.read()

print(text[:1000])

Contents lists available at ScienceDirect
Artificial Intelligence In Medicine
journal homepage: www.elsevier.com/locate/artmed

Electrohysterography in modern obstetrics: Advances in signal processing,
machine learning, and clinical applications
Katerina Barnova a,b
, Radek Martinek a
, Jitka Horakova c, Ondrej Simetka c
,
Radana Vilimkova Kahankova a
,∗
a VSB – Technical University of Ostrava, Department of Cybernetics and Biomedical Engineering, 17. listopadu 2172/15, Ostrava, 70800, Czechia
b Hospital AGEL Trinec-Podlesi, Telemedicine Center, Konska 453, Trinec, 739 61, Czechia
c University Hospital Ostrava, Department of Obstetrics and Gynecology, 17. listopadu 1790/5, Ostrava, 708 00, Czechia
A R T I C L E  I N F O
Keywords:
Uterine electromyography
Uterine activity monitoring
EHG signal processing
Uterine contractions detection
Term/preterm birth prediction
Pregnancy/labor classification

A B S T R A C T
Electrohysterography (EHG) represents a promising computational approa

In [13]:
print(len(text), "characters")
print(len(text.split()), "words")

185718 characters
24185 words

In [14]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

In [15]:
chunks = splitter.split_text(text)

In [16]:
print(len(chunks))

232

In [17]:
print(chunks[0])

Contents lists available at ScienceDirect
Artificial Intelligence In Medicine
journal homepage: www.elsevier.com/locate/artmed

Electrohysterography in modern obstetrics: Advances in signal processing,
machine learning, and clinical applications
Katerina Barnova a,b
, Radek Martinek a
, Jitka Horakova c, Ondrej Simetka c
,
Radana Vilimkova Kahankova a
,∗
a VSB – Technical University of Ostrava, Department of Cybernetics and Biomedical Engineering, 17. listopadu 2172/15, Ostrava, 70800, Czechia
b Hospital AGEL Trinec-Podlesi, Telemedicine Center, Konska 453, Trinec, 739 61, Czechia
c University Hospital Ostrava, Department of Obstetrics and Gynecology, 17. listopadu 1790/5, Ostrava, 708 00, Czechia
A R T I C L E  I N F O
Keywords:
Uterine electromyography
Uterine activity monitoring
EHG signal processing
Uterine contractions detection
Term/preterm birth prediction
Pregnancy/labor classification

A B S T R A C T

In [18]:
print(chunks[1])

Keywords:
Uterine electromyography
Uterine activity monitoring
EHG signal processing
Uterine contractions detection
Term/preterm birth prediction
Pregnancy/labor classification

A B S T R A C T
Electrohysterography (EHG) represents a promising computational approach for non-invasive monitoring of
uterine activity during pregnancy and labor. This review summarizes the advancements in signal processing
techniques and machine learning algorithms that have been applied to enhance the utility of EHG. Key topics
include the extraction and analysis of uterine electrical signals, classification of contractions, and prediction
of obstetric outcomes such as preterm and labor/non-labor states. The review emphasizes computational
methodologies for signal processing and extraction, including empirical mode decomposition or wavelet
transform, and for data classification, such as neural networks or support vector machine, highlighting their

In [19]:
all_chunks = []

In [20]:
for file in txt_files:

    with open(file, "r", encoding="utf-8") as f:
        text = f.read()

    chunks = splitter.split_text(text)

    for i, chunk in enumerate(chunks):

        all_chunks.append({

            "paper": file.stem,

            "chunk_id": i,

            "text": chunk

        })

In [21]:
print(len(all_chunks))

833

In [22]:
all_chunks[0]

{'paper': 'paper1',
 'chunk_id': 0,
 'text': 'Contents lists available at ScienceDirect\nArtificial Intelligence In Medicine\njournal homepage: www.elsevier.com/locate/artmed\n \nElectrohysterography in modern obstetrics: Advances in signal processing, \nmachine learning, and clinical applications\nKaterina Barnova a,b\n, Radek Martinek a\n, Jitka Horakova c, Ondrej Simetka c\n, \nRadana Vilimkova Kahankova a\n,∗\na VSB – Technical University of Ostrava, Department of Cybernetics and Biomedical Engineering, 17. listopadu 2172/15, Ostrava, 70800, Czechia\nb Hospital AGEL Trinec-Podlesi, Telemedicine Center, Konska 453, Trinec, 739 61, Czechia\nc University Hospital Ostrava, Department of Obstetrics and Gynecology, 17. listopadu 1790/5, Ostrava, 708 00, Czechia\nA R T I C L E  I N F O\nKeywords:\nUterine electromyography\nUterine activity monitoring\nEHG signal processing\nUterine contractions detection\nTerm/preterm birth prediction\nPregnancy/labor classification\n \nA B S T R A C T'}

In [23]:
chunks_df = pd.DataFrame(all_chunks)

chunks_df.head()

    paper  chunk_id                                               text
0  paper1         0  Contents lists available at ScienceDirect\nArt...
1  paper1         1  Keywords:\nUterine electromyography\nUterine a...
2  paper1         2  transform, and for data classification, such a...
3  paper1         3  3\n2.1. \nUterine contraction classification ....
4  paper1         4  6\n3.1.1. \nSensing electrodes ..................

In [24]:
chunks_df.groupby("paper").size()

paper
paper1     232
paper10     25
paper2     110
paper3      38
paper4      74
paper5      72
paper6      56
paper7     141
paper8      40
paper9      45
dtype: int64

In [25]:
chunks_df["characters"] = chunks_df["text"].apply(len)

chunks_df["characters"].describe()

count    833.000000
mean     953.333733
std       61.945630
min      161.000000
25%      941.000000
50%      964.000000
75%      982.000000
max      999.000000
Name: characters, dtype: float64

In [26]:
OUTPUT_PATH = PROJECT_PATH / "processed"

OUTPUT_PATH.mkdir(exist_ok=True)

chunks_df.to_csv(
    OUTPUT_PATH / "chunks.csv",
    index=False
)

In [27]:
chunks_df.to_json(
    OUTPUT_PATH / "chunks.json",
    orient="records",
    indent=2
)